# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "http://www.adampreston.org/"

# Author
author:
  name:         Adam Preston
  url:          http://www.adampreston.org
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
